spring:
  application:
    name: TransactionService
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    username: 'phunq'
    password: '123456'
    url: jdbc:postgresql://localhost:5432/transaction
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: false